// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrScs0L0AP1cAyYqQkqzb3IkIoQe6Wi0Q',
    appId: '1:5037567728:web:5b38b1ec4ddbbd5b97dc35',
    messagingSenderId: '5037567728',
    projectId: 'eventoscolibri12',
    authDomain: 'eventoscolibri12.firebaseapp.com',
    storageBucket: 'eventoscolibri12.appspot.com',
    measurementId: 'G-LBEK1881WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfWYgr3bFjFw8o5dXJfcwm4uEqQls3mLs',
    appId: '1:5037567728:android:de1b5dca7afc1b9597dc35',
    messagingSenderId: '5037567728',
    projectId: 'eventoscolibri12',
    storageBucket: 'eventoscolibri12.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrScs0L0AP1cAyYqQkqzb3IkIoQe6Wi0Q',
    appId: '1:5037567728:web:d46537fcdefa590b97dc35',
    messagingSenderId: '5037567728',
    projectId: 'eventoscolibri12',
    authDomain: 'eventoscolibri12.firebaseapp.com',
    storageBucket: 'eventoscolibri12.appspot.com',
    measurementId: 'G-EC76YEK5XB',
  );
}
